-- =========== Enable row level security ===========
ALTER TABLE public.chemicals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.directory ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_categories ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_category_to_sds ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mfrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_data_sheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacies ENABLE ROW LEVEL SECURITY;


-- =========== Force row level security ===========
ALTER TABLE public.chemicals FORCE ROW LEVEL SECURITY;
ALTER TABLE public.compounds FORCE ROW LEVEL SECURITY;
ALTER TABLE public.directory FORCE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_categories FORCE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_category_to_sds FORCE ROW LEVEL SECURITY;
-- ALTER TABLE public.hazard_classes FORCE ROW LEVEL SECURITY;
ALTER TABLE public.ingredients FORCE ROW LEVEL SECURITY;
ALTER TABLE public.mfrs FORCE ROW LEVEL SECURITY;
ALTER TABLE public.products FORCE ROW LEVEL SECURITY;
ALTER TABLE public.risk_assessments FORCE ROW LEVEL SECURITY;
ALTER TABLE public.routine_completions FORCE ROW LEVEL SECURITY;
ALTER TABLE public.routines FORCE ROW LEVEL SECURITY;
ALTER TABLE public.safety_data_sheets FORCE ROW LEVEL SECURITY;
ALTER TABLE public.settings FORCE ROW LEVEL SECURITY;
ALTER TABLE public.vendors FORCE ROW LEVEL SECURITY;
ALTER TABLE public.users FORCE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacies FORCE ROW LEVEL SECURITY;