name: Prevent Supabase Pausing
on:
  schedule:
    - cron: '0 12 * * 5'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase (Production)
        shell: bash
        env:
          SUPABASE_DB_PROD_API_KEY: ${{ secrets.SUPABASE_DB_PROD_API_KEY }}
        run: |
          curl --request GET \
          --url 'https://grymjstlzdtkyqfygjtq.supabase.co/rest/v1/chemicals?select=name' \
          --header "apikey: $SUPABASE_DB_PROD_API_KEY"\
          --header "Authorization: Bearer $SUPABASE_DB_PROD_API_KEY"
      - name: Call Supabase (Dev)
        shell: bash
        env:
          SUPABASE_DB_DEV_API_KEY: ${{ secrets.SUPABASE_DB_DEV_API_KEY }}
        run: |
          curl --request GET \
          --url 'https://iwnoybxepxvedtmkduvo.supabase.co/rest/v1/chemicals?select=name' \
          --header "apikey: $SUPABASE_DB_DEV_API_KEY"\
          --header "Authorization: Bearer $SUPABASE_DB_DEV_API_KEY"
